### ISSUE TITLE
How to evaluate the the custom scheduler

### ISSUE THREAD

**Issue by dyyfk** [amarchese96/sophos#1]
I was able to get the scheduler running following the installation guide, but how do I measure the improvement of the custom scheduler over the default one?

Also, is it possible to run only the scheduler without the descheduler. I intended to use this custom scheduler for ml training job and I don't want the pods to be rescheduled.

**Comment by amarchese96** [comment]
Hi @dyyfk,
This framework has been thought for the orchestration of microservices-based applications. In this case,the improvement of the custom scheduler over the default one can be evaluated by measuring the response time of the application. But the framework can be also extended to other scenarios, like the orchestration of machine learning training jobs. The effective application service level indicators (SLI) can change based on the considered scenario.

For the second question, at this moment the descheduler component is a WIP, so by default you don't have automatic rescheduling for your Pods.

**Comment by dyyfk** [comment]
Thanks for your response!
